server:
  port: 8401
spring:
  application:
    name: hystrix-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://nirvana:y1j2l3123321yjl@localhost:8090/eureka
service-url:
  user-service: http://user-service

hystrix:
  dashboard:
    proxy-stream-allow-list: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露hystrix监控端点
